### ISSUE TITLE
Ember-data search result points to Ember

### ISSUE THREAD

**Issue by MarcoUmpierrez** [ember-learn/ember-api-docs#666] opened 2020-01-25 13:40 UTC
Searching for `pluralize` shows this:
![imagen](https://user-images.githubusercontent.com/4463594/73121987-8b60e100-3f7f-11ea-82b1-7233cf2edf7a.png)

which links to the url:
![imagen](https://user-images.githubusercontent.com/4463594/73122003-cf53e600-3f7f-11ea-93f6-0bf4e64a3455.png)

but the correct url is in `ember-data` 
`https://api.emberjs.com/ember-data/3.15/classes/Ember.Inflector/methods/pluralize?anchor=pluralize` 
so it results in a `404`.

**Comment by Gaurav0** [comment] 2020-04-27 15:03
Duplicate of #640

**Closed** 2020-09-18 11:44 UTC
