### ISSUE TITLE
Clicking the 'createRecord' link on this page 404’d

### ISSUE THREAD

**Issue by chrism** [ember-learn/ember-api-docs#721] opened 2020-05-11 17:31 UTC
In fact none of these three links in this section seem to work for me

https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fstore

> createRecord is used for creating new records on the client side. This will return a new record in the created.uncommitted state. In order to persist this record to the backend, you will need to call record.save().

> push is used to notify Ember Data's store of new or updated records that exist in the backend. This will return a record in the loaded.saved state. The primary use-case for store#push is to notify Ember Data about record updates (full or partial) that happen outside of the normal adapter methods (for example SSE or Web Sockets).

> pushPayload is a convenience wrapper for store#push that will deserialize payloads if the Serializer implements a pushPayload method.

Thanks

**Comment by Gaurav0** [comment] 2020-05-11 19:46
Duplicate of #672

**Closed by Gaurav0** 2020-05-11 19:46 UTC
