### ISSUE TITLE
Links between projects appear to be broken

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#243] opened 2017-06-29 18:03 UTC
When clicking the Ember.ArrayProxy link below on https://www.emberjs.com/api-beta/ember-data/2.14.3/classes/DS.RecordArray, my destination link is https://www.emberjs.com/api-beta/ember-data/2.14.3/classes/Ember.ArrayProxy instead of https://www.emberjs.com/api-beta/ember/2.13.3/classes/Ember.ArrayProxy

![screen shot 2017-06-29 at 12 01 40 pm](https://user-images.githubusercontent.com/802505/27702871-c35cbdec-5cc2-11e7-84e9-ba0bf9f51cf7.png)

**Comment by MartinMalinda** [comment] 2017-06-29 18:06
Clicking https://www.emberjs.com/api-beta/ember-data/2.14.3/classes/DS.RecordArray, I am getting Internal Server Error

**Comment by MartinMalinda** [comment] 2017-07-01 15:29
The reason for the 500 and FB breaking is.
The issue is here, where `version` ends up undefined. 
https://github.com/ember-learn/ember-api-docs/blob/a23b453bed45d8a04e9e05acc4419446f5af2439/app/adapters/application.js#L33

It looks like a race condition issue. Trying to access the controller befaure it got its model. I think after the merge of #239 it will be easier to get the version from `metaStore` or `routerService`

**Comment by toddjordan** [comment] 2017-07-06 20:12
looks to be broken until we merge #239  is merged

**Comment by sivakumar-kailasam** [comment] 2017-07-10 16:05
@toddjordan @MartinMalinda this is working in prod now.

**Closed** 2018-01-03 05:22 UTC
Labels: help wanted
