### ISSUE TITLE
Regression: Starting with 2.16 Dash.app search of the docs yields insufficient results

### ISSUE THREAD

**Issue by pichfl** [ember-learn/ember-api-docs#403] opened 2017-12-03 22:50 UTC
2.16 are the first docs based on the new modules. While these should make it easier, the result in Dash is actually a less pleasant search for specific parts of Ember which was very easy in the 2.15 and older docsets.

For example, while looking for a specific computed macro, I could use `computed.` to filter the results to anything in the `Ember.computed` namespace. Now the same query shows no results at all, nor does `@ember/object/computed`. 

![Search for computed in the 2.15 docs](https://user-images.githubusercontent.com/194641/33530683-c5f0e122-d883-11e7-8050-ca19b65f02d2.png)

![Search for computed in the 2.16 docs](https://user-images.githubusercontent.com/194641/33530685-d7b98c10-d883-11e7-958f-07b1c4d60095.png)

The author of Dash provides some information on how the old behavior could be restored: https://kapeli.com/docsets#improveDocset

I think it should be sufficient to generate a SQLite Index file when then docs are generated. Hosting the docset online might be another useful option.

It looks like the "official" docsets were generated by scraping this sites using HTTrack Website Copier: 
- emberjs.com/api/ember/2.15/namespaces/Ember.html
- emberjs.com/api/ember-data/2.14/namespaces/DS.html
- guides.emberjs.com/v2.15.0/index.html

This in itself presents an interesting issue as Ember Data and Ember seem to be locked together. 

As Dash and its siblings on other platforms are quite useful, I think it would be nice to see the Ember docs in their full range inside the application. Offline-use and fast search included. 

I might have some time over the holidays to tackle this in some way, however I do not yet have experience with YUIDocs and/or the additional building blocks of this Ember app. 

From what I see there are the following steps:

- [ ] Static docs without requirement for JavaScript (JS is possible inside Dash, but it might be easier)
- [ ] (Optionally) Split Ember and Ember Data into two separate Docsets
- [ ] Documentation Index in SQL - Probably based on the JSON API data
- [ ] Wrapping the docset as file for download - Maybe when building a new version for the web?
- [ ] Provide Docset Feed - Should be easily generated by a Build task
- [ ] Contact Dash.app author for release or provide URL to feed on Ember Docs website 

There are a few open questions like what paths should be pushed into the search index etc. the docset for D3 might be an inspiration here. D3 4.x is based on ES6 modules and the generator for their docs inside Dash provides very usable results: https://github.com/exlee/d3-dash-gen

EDIT: I just found #299 which contains references to Dash.app as well.

**Comment by sivakumar-kailasam** [comment] 2017-12-07 18:57
@pichfl Thank you for bringing this up. We've broken dash docs early this year when we're moving to the new API docs & we worked with the author to fix it. Its broken again because we've rewritten our URLs to support the new modules API recently & also changed the page structures as well.

I like the idea of us generating the SQLite index file. We can definitely generate it as we generate new docs. If you're interested in contributing to this, please look at github.com/ember-learn/ember-jsonapi-docs which generates our API docs. If you need to discuss any ideas we can do it over this issue or over the ember slack.

**Comment by kategengler** [comment] 2018-01-04 17:36
@pichfl Are you still interested in tackling this?

I've run into this as well. Another example: Searching for `service` will find `@ember/service` and from there I can see the docs on `inject`, but if I search for `inject`, I will not see that entry.

Since there is no longer search on the API docs on emberjs.com, I very often rely on Dash.

**Comment by pichfl** [comment] 2018-01-04 20:05
My vacation took a different direction, but yes, I'm still looking into generating the SQLite index. I don't have a definite deadline planned for this though, so if you have more time to spare, feel free to take over here. I'll try to follow up.

**Comment by acorncom** [comment] 2018-01-30 07:38
Search for api docs on emberjs.com just landed again 🎉 We're still working out the kinks and don't intend for that to replace this work. But just as an FYI ...

**Comment by sivakumar-kailasam** [comment] 2018-02-18 21:15
@pichfl @kategengler We reached out to the developer of Dash and he has confirmed that he's able to work with our current implementation of API docs without any issues.  He has asked us to direct any issues that our community might face by reaching out to him with details via the support email, `support at kapeli dot com`. In case there are future issues where it needs resolution from our end, we'll be glad to help out. 

In case you would still like to work on what you've proposed, please feel free to reopen this issue & raise a PR :)

**Closed by sivakumar-kailasam** 2018-02-18 21:15 UTC
Labels: help wanted
