### ISSUE TITLE
Internal urls have a stray "api" segment that breaks them

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#623] opened 2019-07-16 03:20 UTC
In the ember.js codebase, any url in the form similar to `[EmberObject](/ember/release/classes/EmberObject)` renders as `http://api.emberjs.com/api/ember/release/classes/EmberObject` (note that the word `api` shows up twice, and it shouldn't)

This seems to be true going back multiple versions, but here's there are recent examples on this page: http://api.emberjs.com/ember/3.11/classes/Component

**Comment by jenweber** [comment] 2019-07-18 13:14
Be sure to check recently merged prs to see if something changed

**Comment by toddjordan** [comment] 2019-09-02 16:41
This likely happened when we maded the transition from ember.js.com/api -> api.emberjs.com.  Easiest fix would be to just create an internal "api" route that redirects api/* to /*

**Comment by toddjordan** [comment] 2019-09-02 16:56
duplicate of #613

**Closed** 2019-09-02 16:57 UTC
Labels: 👯‍♂️duplicate
